# Generated by Django 3.1.14 on 2023-09-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20230920_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='products',
        ),
        migrations.AddField(
            model_name='lessons',
            name='products',
            field=models.ManyToManyField(to='API.Products', verbose_name='Продукт'),
        ),
    ]
