# Generated by Django 3.1.14 on 2023-09-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20230921_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'default_related_name': 'product', 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Доступ', 'verbose_name_plural': 'Доступы'},
        ),
        migrations.AlterField(
            model_name='lessons',
            name='products',
            field=models.ManyToManyField(related_name='product', to='API.Products', verbose_name='Продукт'),
        ),
    ]
