# Generated by Django 3.1.14 on 2023-09-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20230921_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='lessons',
            name='products',
            field=models.ManyToManyField(to='API.Products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(related_name='products', to='API.Products', verbose_name='Продукт'),
        ),
    ]
