# Generated by Django 3.1.14 on 2023-09-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20230921_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
